#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: the YouTube OAuth bootstrap for paper-cast (issue #3).
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=10

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(cd "$SCRIPT_DIR/.." && pwd)"
CONFIG_DIR="$HOME/.config/paper-cast"
CLIENT_SECRET="$CONFIG_DIR/client_secret.json"
TOKEN_FILE="$CONFIG_DIR/youtube_token.json"
CLIP="${TMPDIR:-/tmp}/paper-cast-bootstrap-test.mp4"

APP_NAME="paper-cast"

# The consent screen needs a homepage and a privacy policy; this repo is both.
# Read the URLs off the remote so a fork points at itself, not at the original.
REMOTE_URL="$(git -C "$REPO" remote get-url origin 2>/dev/null || true)"
HOME_URL="$(printf '%s' "$REMOTE_URL" | sed -E 's#^git@([^:]+):#https://\1/#; s#\.git$##')"
[[ "$HOME_URL" == https://* ]] || HOME_URL="https://github.com/TiagoVello/paper-cast"
# The policy has to be on the default branch, which is what Google will fetch.
PRIVACY_URL="$HOME_URL/blob/main/PRIVACY.md"
AUTHORIZED_DOMAIN="$(printf '%s' "$HOME_URL" | awk -F/ '{print $3}')"

# Where paper-cast's own policy lives. Stage 4 falls back to it for anybody
# running this out of a plugin checkout, which is a clone of somebody else's
# repo and cannot publish a policy of its own (#12).
UPSTREAM_HOME_URL="https://github.com/TiagoVello/paper-cast"
UPSTREAM_PRIVACY_URL="$UPSTREAM_HOME_URL/blob/main/PRIVACY.md"
SUMMARY_FILE="$CONFIG_DIR/bootstrap-summary.md"

# Re-run memory lives with the other per-machine config, not in the repo.
mkdir -p "$CONFIG_DIR"
chmod 700 "$CONFIG_DIR"
ENV_FILE="$CONFIG_DIR/bootstrap.env"

# copy VALUE puts it on the clipboard, so every field is a paste, not a retype.
copy() {
  if command -v wl-copy >/dev/null 2>&1 && printf '%s' "$1" | wl-copy 2>/dev/null; then
    printf '  %s⧉ on your clipboard:%s %s\n' "$GREEN" "$RESET" "$1"
  else
    printf '  %s→%s %s\n' "$BLUE" "$RESET" "$1"
  fi
}

# live URL: true when the URL answers 200, i.e. Google will be able to fetch it.
live() { curl -fsL -o /dev/null --max-time 20 "$1"; }

# pushable: this checkout has an origin we could push to, and something to push.
# A plugin installed by `omarchy plugin add` is a clone of somebody else's repo,
# so the push offer in stage 4 has to disappear for everyone but its author.
pushable() {
  local branch
  git -C "$REPO" rev-parse --git-dir >/dev/null 2>&1 || return 1
  git -C "$REPO" remote get-url --push origin >/dev/null 2>&1 || return 1
  branch=$(git -C "$REPO" symbolic-ref --quiet --short HEAD) || return 1
  git -C "$REPO" rev-parse --quiet --verify "origin/$branch" >/dev/null 2>&1 || return 1
  [[ -n "$(git -C "$REPO" log --oneline "origin/$branch..$branch" 2>/dev/null)" ]]
}

# Every program the ten stages need, checked before the first of them rather
# than at stage 9: a quarter of an hour of console work should not end on a
# missing ffmpeg. `paper-cast setup` runs this after installing them (#12).
MISSING=""
for _tool in python3 curl ffmpeg awk sed stat mktemp; do
  command -v "$_tool" >/dev/null 2>&1 || MISSING="$MISSING $_tool"
done
if [[ -n "$MISSING" ]]; then
  printf 'bootstrap_youtube.sh: not on PATH:%s\n' "$MISSING" >&2
  printf 'Run `paper-cast setup`, which installs them, and it will come back here.\n' >&2
  exit 1
fi

banner "paper-cast: YouTube OAuth bootstrap"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Create the GCP project"
say "Every OAuth client belongs to a project. One project, used forever."
say "You do not need an existing project, and you do not need billing: the"
say "YouTube Data API's free quota covers this and no card is asked for."
note "First time in the Cloud console? It asks you to accept the terms and"
note "pick a country before it shows you anything. That is the only gate."
open_url "https://console.cloud.google.com/projectcreate"
step "Name it something you will recognise, e.g. paper-cast."
step "Click CREATE, wait for the notification, then open the project."
step "Copy the *project ID* (under the name; it may have a number suffix)."
note "The ID, not the display name: 'paper-cast-472119', not 'paper-cast'."
ask GCP_PROJECT_ID "Paste the project ID:"
for _attempt in 1 2 3; do
  [[ -n "$GCP_PROJECT_ID" ]] && break
  warn "The project ID is needed to open the right pages."
  ask GCP_PROJECT_ID "Paste the project ID:"
done
if [[ -z "$GCP_PROJECT_ID" ]]; then
  warn "No project ID given; nothing else can be opened. Re-run when you have it."
  exit 1
fi
write_env GCP_PROJECT_ID "$GCP_PROJECT_ID"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Enable the YouTube Data API v3"
say "The API has to be switched on for this project before it answers at all."
open_url "https://console.cloud.google.com/apis/library/youtube.googleapis.com?project=$GCP_PROJECT_ID"
step "Click ENABLE."
step "Wait until the page turns into the API's dashboard ('API enabled')."
note "Already enabled? The button reads MANAGE instead. That is fine."
pause "Enabled? Press Enter."

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Create the consent screen"
say "This is the screen you will click through when authorising, once."
open_url "https://console.cloud.google.com/auth/overview?project=$GCP_PROJECT_ID"
step "Click GET STARTED if the project has no auth config yet."
step "App name: $APP_NAME. User support email: your own address."
step "Audience: choose EXTERNAL. (Internal needs a Workspace org.)"
step "Contact information: your own address. Agree, then CREATE."
note "No test users needed: stage 6 publishes the app, which retires that list."
note "Already configured? Skip straight on; stage 4 fixes up the details."
pause "Consent screen exists? Press Enter."

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Branding: what production mode demands"
say "Publishing to production is refused until the app has a name, a support"
say "email, a homepage URL and a privacy policy URL. The repo is the homepage,"
say "and PRIVACY.md in it is the policy."
say ""

if ! live "$PRIVACY_URL"; then
  warn "The privacy policy is not reachable yet:"
  note "  $PRIVACY_URL"
  if pushable; then
    say "It is committed locally but not pushed, so Google cannot see it."
    if confirm "Push it to GitHub now (git push origin main)?"; then
      git -C "$REPO" push origin main &&
        printf '  %s✓ pushed%s\n' "$GREEN" "$RESET" ||
        warn "Push failed; the fallback below works just as well."
    fi
  else
    say "This checkout has nothing to push, or no rights to push it — which is"
    say "the normal case: a plugin checkout is a clone of somebody else's repo."
  fi
  if live "$PRIVACY_URL"; then
    printf '  %s✓ privacy policy is live%s\n' "$GREEN" "$RESET"
  elif live "$UPSTREAM_PRIVACY_URL"; then
    # The policy describes what paper-cast does with your data, and that is the
    # same program whoever is running it, so the upstream copy is the right one
    # to point a consent screen at when your own fork has no published copy.
    HOME_URL="$UPSTREAM_HOME_URL"
    PRIVACY_URL="$UPSTREAM_PRIVACY_URL"
    AUTHORIZED_DOMAIN="$(printf '%s' "$HOME_URL" | awk -F/ '{print $3}')"
    printf '  %s✓ using paper-cast'"'"'s own published policy%s\n' "$GREEN" "$RESET"
    note "  $PRIVACY_URL"
  else
    warn "No reachable privacy policy. Google will reject the URL."
    SKIPPED+=("publish PRIVACY.md somewhere Google can fetch it")
  fi
else
  printf '  %s✓ privacy policy is live%s\n' "$GREEN" "$RESET"
fi

say ""
open_url "https://console.cloud.google.com/auth/branding?project=$GCP_PROJECT_ID"
step "App name: $APP_NAME"
step "User support email: pick your own address from the dropdown."
say ""
step "Authorized domains → + ADD DOMAIN. Do this BEFORE the two URLs below,"
say "  or the console rejects them as unauthorised."
copy "$AUTHORIZED_DOMAIN"
pause "Domain added? Press Enter for the homepage URL."
say ""
step "App domain → Application home page:"
copy "$HOME_URL"
pause "Pasted? Press Enter for the privacy policy URL."
say ""
step "App domain → Application privacy policy link:"
copy "$PRIVACY_URL"
pause "Pasted? Press Enter."
say ""
step "Application terms of service link: leave empty, it is not required."
step "Developer contact information: your own email address."
step "Click SAVE."
say ""
note "If the console refuses github.com as an authorized domain, stop here and"
note "say so: the fallback is GitHub Pages on this repo, which takes two clicks."
pause "Saved? Press Enter."
write_env BRANDING_HOME_URL "$HOME_URL"
write_env BRANDING_PRIVACY_URL "$PRIVACY_URL"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Declare the upload scope"
say "One scope, and only one: permission to upload a video."
open_url "https://console.cloud.google.com/auth/scopes?project=$GCP_PROJECT_ID"
step "ADD OR REMOVE SCOPES, then filter for 'youtube.upload'."
copy "https://www.googleapis.com/auth/youtube.upload"
step "Tick it, click UPDATE, then SAVE."
note "Google lists it as a sensitive scope. Expected; it changes nothing below."
pause "Scope saved? Press Enter."

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Publish the app to production"
warn "The one step that must not be skipped."
say "A consent screen left in Testing issues refresh tokens that expire after"
say "7 days. An unattended paper-cast would then die weekly with invalid_grant."
say ""
say "Publishing is NOT verification: no audit, no review. It only needs the"
say "Branding fields from stage 4 to be filled in."
open_url "https://console.cloud.google.com/auth/audience?project=$GCP_PROJECT_ID"
step "Under Publishing status, click PUBLISH APP."
step "A dialog will mention verification for sensitive scopes. Confirm anyway."
note "The app stays unverified on purpose. You will see an 'unverified app'"
note "warning when authorising, and uploads are force-locked to private, which"
note "is exactly what paper-cast wants."
say ""
note "Refused, still naming a missing field? Go back to stage 4's page and fill"
note "the one it names; the error says which."
say ""
if confirm "Does Publishing status now read 'In production'?"; then
  CONSENT_SCREEN_PUBLISHED="in-production"
  write_env CONSENT_SCREEN_PUBLISHED "$CONSENT_SCREEN_PUBLISHED"
else
  warn "Left in Testing: the refresh token will die in 7 days."
  SKIPPED+=("publish the consent screen at https://console.cloud.google.com/auth/audience?project=$GCP_PROJECT_ID")
fi

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Create the Desktop OAuth client"
say "Desktop app is the type that gets a loopback redirect and an 'installed'"
say "client secret, which is what scripts/youtube_auth.py expects."
open_url "https://console.cloud.google.com/auth/clients?project=$GCP_PROJECT_ID"
step "CREATE CLIENT. Application type: Desktop app."
step "Name it $APP_NAME. CREATE."
step "In the dialog, DOWNLOAD JSON. (You can re-download it later.)"
pause "Downloaded? Press Enter."

DOWNLOADED=""
LATEST=$(ls -t "$HOME"/Downloads/client_secret*.json 2>/dev/null | head -n1 || true)
if [[ -n "$LATEST" ]]; then
  say ""
  say "Found: $LATEST"
  if confirm "Use that file?"; then DOWNLOADED="$LATEST"; fi
fi
for _attempt in 1 2 3; do
  [[ -f "$DOWNLOADED" ]] && break
  ask DOWNLOADED_PATH "Path to the downloaded JSON:"
  DOWNLOADED="${DOWNLOADED_PATH/#\~/$HOME}"
  [[ -f "$DOWNLOADED" ]] || warn "No file at $DOWNLOADED"
done
if [[ ! -f "$DOWNLOADED" ]]; then
  warn "Could not find the downloaded client secret. Re-run once you have it;"
  warn "everything up to here is remembered."
  exit 1
fi

if ! python3 -c 'import json,sys; d=json.load(open(sys.argv[1])); sys.exit(0 if "installed" in d else 1)' "$DOWNLOADED"; then
  warn "That JSON has no 'installed' block, so it is not a Desktop app client."
  warn "Go back and create the client with type Desktop app."
  exit 1
fi
if [[ "$DOWNLOADED" != "$CLIENT_SECRET" ]]; then
  mv "$DOWNLOADED" "$CLIENT_SECRET"
fi
chmod 600 "$CLIENT_SECRET"
printf '  %s✓ placed%s %s (mode 600)\n' "$GREEN" "$RESET" "$CLIENT_SECRET"

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Authorise: the one interactive consent"
say "This opens the consent screen, catches Google's redirect on a loopback"
say "port, and writes the refresh token to disk at mode 600."
say ""
step "Pick the Google account that owns the YouTube channel."
step "At 'Google hasn't verified this app': Advanced, then Go to $APP_NAME."
step "Leave the YouTube permission TICKED, then Continue."
note "An unticked box still returns a token, just one that cannot upload."
say ""
pause "Ready? Press Enter to open the consent screen."
if python3 "$SCRIPT_DIR/youtube_auth.py" authorize; then
  printf '  %s✓ refresh token stored%s\n' "$GREEN" "$RESET"
else
  warn "Authorisation failed. Re-run this wizard once the cause is fixed."
  exit 1
fi
TOKEN_MODE=$(stat -c '%a' "$TOKEN_FILE")
say "Token file mode: $TOKEN_MODE"
[[ "$TOKEN_MODE" == "600" ]] || warn "Expected mode 600 on $TOKEN_FILE"

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "Prove a private upload"
say "A throwaway 5-second clip, uploaded private, to show the chain works"
say "before any of the pipeline depends on it."
say ""

# The one stage that is not idempotent: it puts a real video on the channel
# every time, against a budget of 100 videos.insert calls a day. A re-run that
# stopped in stage 10 should not spend a second one (#12).
PROVEN=$(_existing TEST_VIDEO_ID || true)
VIDEO_ID="$PROVEN"
if [[ -n "$PROVEN" ]]; then
  say "A previous run already uploaded $PROVEN from this machine, so the"
  say "credential is proven. Uploading again spends another of the day's 100."
  say ""
  if confirm "Upload a second test video anyway?"; then
    VIDEO_ID=""
  else
    say "Checking the stored credential instead..."
    if python3 "$SCRIPT_DIR/youtube_auth.py" refresh >/dev/null; then
      printf '  %s✓ the credential still works%s\n' "$GREEN" "$RESET"
    else
      warn "The stored token no longer refreshes; re-run stage 8 by hand."
      SKIPPED+=("re-authorise: python3 $SCRIPT_DIR/youtube_auth.py authorize")
    fi
  fi
fi

if [[ -z "$VIDEO_ID" ]]; then
step "Building the clip with ffmpeg..."
ffmpeg -y -loglevel error \
  -f lavfi -i color=c=0x1d2021:s=1280x720 \
  -f lavfi -i anullsrc=r=48000:cl=stereo \
  -t 5 -c:v libx264 -tune stillimage -pix_fmt yuv420p -r 2 -g 4 \
  -c:a aac -b:a 128k -ar 48000 -movflags +faststart "$CLIP"
say "  $CLIP ($(du -h "$CLIP" | cut -f1))"
say ""
step "Uploading..."
UPLOAD_LOG="${TMPDIR:-/tmp}/paper-cast-upload.log"
if python3 "$SCRIPT_DIR/youtube_auth.py" upload "$CLIP" \
     --title "paper-cast bootstrap test" \
     --description "Throwaway upload proving the paper-cast credential works." \
     | tee "$UPLOAD_LOG"; then
  VIDEO_ID=$(awk '/^Uploaded /{print $2}' "$UPLOAD_LOG")
  write_env TEST_VIDEO_ID "$VIDEO_ID"
  say ""
  if confirm "Open YouTube Studio to confirm it landed as private?"; then
    open_url "https://studio.youtube.com/video/$VIDEO_ID/edit"
    pause "Confirmed? Press Enter. (Delete it there whenever you like.)"
  fi
else
  warn "Upload failed; see the output above."
  SKIPPED+=("prove a private upload: python3 $SCRIPT_DIR/youtube_auth.py upload $CLIP")
  VIDEO_ID=""
fi
fi  # end of the upload, skipped when an earlier run already proved the credential

# ── 10 ────────────────────────────────────────────────────────────────────
stage "Write down what was configured"
PUBLISHED=$([[ -n "${CONSENT_SCREEN_PUBLISHED:-}" ]] && echo "yes, In production" || echo "NOT PUBLISHED - still in Testing")
cat > "$SUMMARY_FILE" <<SUMMARY
# paper-cast YouTube bootstrap

Configured on this machine on $(date -I).

- **GCP project id**: \`$GCP_PROJECT_ID\`
- **YouTube Data API v3**: enabled on that project.
- **OAuth client**: type Desktop app, scope \`https://www.googleapis.com/auth/youtube.upload\`.
- **Consent screen published to production**: $PUBLISHED. This is what keeps the
  refresh token from expiring after 7 days; it is not verification, and the app
  stays unverified on purpose (uploads force-locked to private).
- **Client secret on disk**: \`~/.config/paper-cast/client_secret.json\` (mode 600).
- **Refresh token on disk**: \`~/.config/paper-cast/youtube_token.json\` (mode 600).
- **Private upload confirmed**: video \`${VIDEO_ID:-(not uploaded)}\`, privacyStatus \`private\`.

### Branding

Production mode is refused until the Branding page has an app name, a support
email, a **homepage URL** and a **privacy policy URL**. Settled by pointing both
at this repo: homepage \`$HOME_URL\`,
privacy policy \`$PRIVACY_URL\` (the
repo's \`PRIVACY.md\`), with \`$AUTHORIZED_DOMAIN\` as the authorized domain.

Re-check the credential any time with:

    python3 $SCRIPT_DIR/youtube_auth.py refresh
SUMMARY
say "Written to:"
say "  $SUMMARY_FILE"
pause "Press Enter for the summary."

finish
